<a href="https://colab.research.google.com/github/maheshkumar30/DataScience/blob/main/GenAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**NLP Piepline**

In [ ]:
!pip install nltk

In [ ]:
from nltk.tokenize import word_tokenize, sent_tokenize

import nltk

nltk.download('punkt_tab')

text = 'Hello! How are you doing? I am learning NLP. It is great'

sentences = sent_tokenize(text)

print(sentences)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['Hello!', 'How are you doing?', 'I am learning NLP.', 'It is great']


In [ ]:
word_tokenize(text)

['Hello',
 '!',
 'How',
 'are',
 'you',
 'doing',
 '?',
 'I',
 'am',
 'learning',
 'NLP',
 '.',
 'It',
 'is',
 'great']

In [ ]:
list(text)

['H',
 'e',
 'l',
 'l',
 'o',
 '!',
 ' ',
 'H',
 'o',
 'w',
 ' ',
 'a',
 'r',
 'e',
 ' ',
 'y',
 'o',
 'u',
 ' ',
 'd',
 'o',
 'i',
 'n',
 'g',
 '?',
 ' ',
 'I',
 ' ',
 'a',
 'm',
 ' ',
 'l',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 ' ',
 'N',
 'L',
 'P',
 '.',
 ' ',
 'I',
 't',
 ' ',
 'i',
 's',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't']

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
text = 'Hello! How are you doing? I am learning NLP. It is great'

stop_words = set(stopwords.words('english'))

words = text.lower().split()

print(words)

['hello!', 'how', 'are', 'you', 'doing?', 'i', 'am', 'learning', 'nlp.', 'it', 'is', 'great']


In [ ]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
x = [word for word in words if word not in stop_words]
x

['hello!', 'doing?', 'learning', 'nlp.', 'great']

In [ ]:
from nltk.stem import PorterStemmer, SnowballStemmer, LancasterStemmer

porter = PorterStemmer()
[porter.stem(i) for i in x ]

['hello!', 'doing?', 'learn', 'nlp.', 'great']

In [ ]:
snowball =  SnowballStemmer('english')
[snowball.stem(i) for i in x ]

['hello!', 'doing?', 'learn', 'nlp.', 'great']

In [ ]:
lancaster = LancasterStemmer()
[lancaster.stem(i) for i in x ]

['hello!', 'doing?', 'learn', 'nlp.', 'gre']

In [ ]:
import spacy
from spacy.lang.en.examples import sentences



nlp = spacy.load("en_core_web_sm")
doc = nlp(sentences[0])
print(doc.text)
for token in doc:
    print(token.text)

Apple is looking at buying U.K. startup for $1 billion
Apple
is
looking
at
buying
U.K.
startup
for
$
1
billion


In [ ]:
import spacy

In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
text = 'In general, spaCy expects all pipeline packages to follow the naming convention of'

doc = nlp(text)
for token in doc:
  print(token.lemma_)

in
general
,
spacy
expect
all
pipeline
package
to
follow
the
name
convention
of


**Bag of word and TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# We will create some sample data ---> Spam and Ham

corpus = ['Congratulations! You have won a $1000 Walmart gift card. Click here to claim your prize.', # Spam
          'Hey, are we still meeting for lunch tomorrow?', # Ham
          'URGENT: Your bank account has been compromised. Click here to verify your identity.', # Spam
          'Just a reminder about the team meeting at 3 PM today.', # Ham
          'You have been selected for a free cruise! Call now to claim your prize.', # Spam
          'Can you please send me the report by end of day?'] # Ham

label = ['Spam', 'Ham', 'Spam', 'Ham', 'Spam', 'Ham']

vec = CountVectorizer()

X = vec.fit_transform(corpus)

print(X.toarray())

[[1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 2]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1
  0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0
  0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0
  1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0]]


In [ ]:
vec.get_feature_names_out()

array(['1000', 'about', 'account', 'are', 'at', 'bank', 'been', 'by',
       'call', 'can', 'card', 'claim', 'click', 'compromised',
       'congratulations', 'cruise', 'day', 'end', 'for', 'free', 'gift',
       'has', 'have', 'here', 'hey', 'identity', 'just', 'lunch', 'me',
       'meeting', 'now', 'of', 'please', 'pm', 'prize', 'reminder',
       'report', 'selected', 'send', 'still', 'team', 'the', 'to',
       'today', 'tomorrow', 'urgent', 'verify', 'walmart', 'we', 'won',
       'you', 'your'], dtype=object)

**TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [ ]:
corpus = ['Congratulations! You have won a $1000 Walmart gift card. Click here to claim your prize.', # Spam
          'Hey, are we still meeting for lunch tomorrow?', # Ham
          'URGENT: Your bank account has been compromised. Click here to verify your identity.', # Spam
          'Just a reminder about the team meeting at 3 PM today.', # Ham
          'You have been selected for a free cruise! Call now to claim your prize.', # Spam
          'Can you please send me the report by end of day?'] # Ham

tfidf = TfidfVectorizer()

x = tfidf.fit_transform(corpus)

# print(x.toarray())

df = pd.DataFrame(
    x.toarray(),
    columns = tfidf.get_feature_names_out(),
)
df

,1000,about,account,are,at,bank,been,by,call,can,card,claim,click,compromised,congratulations,cruise,day,end,for,free,gift,has,have,here,hey,identity,just,lunch,me,meeting,now,of,please,pm,prize,reminder,report,selected,send,still,team,the,to,today,tomorrow,urgent,verify,walmart,we,won,you,your
0,0.30429,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.30429,0.249522,0.249522,0.000000,0.30429,0.000000,0.000000,0.000000,0.000000,0.000000,0.30429,0.000000,0.249522,0.249522,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.249522,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.210664,0.000000,0.000000,0.000000,0.000000,0.30429,0.000000,0.30429,0.210664,0.210664
1,0.00000,0.000000,0.000000,0.368985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.302573,0.000000,0.00000,0.000000,0.000000,0.000000,0.368985,0.000000,0.000000,0.368985,0.000000,0.302573,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.368985,0.000000,0.000000,0.000000,0.000000,0.368985,0.000000,0.000000,0.00000,0.368985,0.00000,0.000000,0.000000
2,0.00000,0.000000,0.295996,0.000000,0.000000,0.295996,0.242721,0.000000,0.000000,0.000000,0.00000,0.000000,0.242721,0.295996,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.295996,0.000000,0.242721,0.000000,0.295996,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.204922,0.000000,0.000000,0.295996,0.295996,0.00000,0.000000,0.00000,0.000000,0.409843
3,0.00000,0.346171,0.000000,0.000000,0.346171,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.346171,0.000000,0.000000,0.283865,0.000000,0.000000,0.000000,0.346171,0.000000,0.346171,0.000000,0.000000,0.000000,0.000000,0.346171,0.283865,0.000000,0.346171,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000
4,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.261944,0.000000,0.319438,0.000000,0.00000,0.261944,0.000000,0.000000,0.00000,0.319438,0.000000,0.000000,0.261944,0.319438,0.00000,0.000000,0.261944,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.319438,0.000000,0.000000,0.000000,0.261944,0.000000,0.000000,0.319438,0.000000,0.000000,0.000000,0.000000,0.221151,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.221151,0.221151
5,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.313856,0.000000,0.313856,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.313856,0.313856,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.313856,0.000000,0.000000,0.313856,0.313856,0.000000,0.000000,0.000000,0.313856,0.000000,0.313856,0.000000,0.000000,0.257366,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.217286,0.000000


**Vector Embedding**

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 23.1 MB/s eta 0:00:00


In [ ]:
from gensim.models import Word2Vec

sentences = [['King', 'is', 'a', 'royal', 'man'],
             ['Queen', 'is', 'a', 'royal', 'woman'],
             ['Man', 'is', 'strong', 'being'],
             ['Woman', 'is', 'beautiful', 'being']]

model = Word2Vec(
    sentences,
    vector_size=100, # embedding dimension
    window=5,
    min_count=1,
    workers=1
)

# print(model.wv['King'])

print(model.wv.most_similar('King', topn=3))

[('royal', 0.17272792756557465), ('Woman', 0.16694682836532593), ('Man', 0.11118276417255402)]


In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
from sentence_transformers.util import cos_sim

In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

words = ['king','man']

unrelated = ['Man','Queen']

embed1 = model.encode(unrelated)
embed2 = model.encode(words)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [ ]:
print(cos_sim(embed1[0], embed1[1]))
print(cos_sim(embed2[0], embed2[1]))


tensor([[0.2541]])
tensor([[0.3216]])


In [ ]:
import tensorflow as tf
import numpy as np
from collections import Counter
import random

# phase 1: Let's Prepare Data -> Simple English to hindi Sentences
# In real life project, We would have to load from a huge text corpus

data = [
    ("I am happy", "मैं खुश हूँ"),
    ("You are sad", "तुम उदास हो"),
    ("She is tired", "वह थकी हुई है"),
    ("We are hungry", "हम भूखे हैं"),
    ("He is angry", "वह गुस्से में है"),
    ("They are busy", "वे व्यस्त हैं"),
    ("I am cold", "मुझे ठंड लग रही है"),
    ("You are late", "तुम देर से हो"),
    ("She is happy", "वह खुश है"),
    ("We are ready", "हम तैयार हैं")
]
print(len(data))

# Function that builds a Vocabulary
def build_vocabulary(sentences):
    tokens = Counter()
    for sent in sentences: tokens.update(sent.split()) # Counting all words
    # special Tokens
    # <PAD> = 0 : Used to fill empty space so all sentences have same length
    # <SOS> = 1: Start of Sentence (Tells Decoder to start generating from here)
    # <EOS> = 2: End of Sentence (Tells Decoder to stop generating)
    vocab = {"<PAD>":0,"<SOS>":1,"<EOS>":2}

    #assign ID starting from 3 because 0,1,2 are reserved for special tokens
    for i, token in enumerate(tokens.keys(),3): vocab[token] = i
    return vocab

# print(build_vocabulary(data[0])) # Corrected to show a vocabulary example

# Helper Function to convert sentence string into a list of number (indicies)
def sentence_to_indices(sent,vocab):
    # we are sandwiching the sentence with <SOS> and <EOS>
    return [vocab["<SOS>"]] + [vocab.get(t,0) for t in sent.split()] + [vocab["<EOS>"]]

# Let's Create Vocabs
eng_vocab = build_vocabulary([s[0] for s in data]) # Input Language
hindi_vocab = build_vocabulary([s[1] for s in data]) # output Language

print("English Vocab Size: ",len(eng_vocab))
print("Hindi Vocab Size: ",len(hindi_vocab))
print("="*50)
print(eng_vocab)
print("="*50)
print(hindi_vocab)

# we will convert all the text data into Number sequence
# we use 'pad_Sequence' to ensure every senetnce in the batch has the exact same lenght
# If a sentence is short , it will be padded with 0s at the end
src_data = tf.keras.preprocessing.sequence.pad_sequences(
    [sentence_to_indices(s[0],eng_vocab) for s in data],
    padding='post', value = 0
)

tgt_data = tf.keras.preprocessing.sequence.pad_sequences(
    [sentence_to_indices(s[1],hindi_vocab) for s in data],
    padding='post', value = 0
)

print("Source Data: ",src_data)
print("="*50)
print("Target Data: ",tgt_data)

# Phase 2: Building the Model



# The Encoder: It read the input english sentences
class Encoder(tf.keras.Model):
    def __init__(self,input_size, embed_size, hidden_size):
        super(Encoder, self).__init__()
        # Embedding Layer: It will convert the word IDs(int) into dense vectors (list of decimals)
        self.embedding = tf.keras.layers.Embedding(input_size, embed_size)
        # LSTM Layer: It will process the sequence of vectors
        # return_state=True -> It will return the final hidden state and cell state
        # We only care about the final hidden state and cell state
        self.lstm = tf.keras.layers.LSTM(hidden_size, return_state=True)

    def call(self,x):
        embedded = self.embedding(x)
        # we will ignore the ouptu (_) and only keep the states (h,c)
        _, h, c = self.lstm(embedded)
        return h, c # Context Vector

# The Decoder: It will generate the output sequence
class Decoder(tf.keras.Model):
    def __init__(self,output_size, embed_size, hidden_size):
        super(Decoder,self).__init__()
        # Embedding Layer: It will convert the word IDs(int) into dense vectors (list of decimals)
        self.embedding = tf.keras.layers.Embedding(output_size, embed_size)
        # LSTM for Decoder
        # return_sequences=True -> It will return the output for every time step Because we need to pass it to the dense layer
        self.lstm = tf.keras.layers.LSTM(hidden_size, return_sequences=True, return_state=True)

        # dense Layer: Convert LSTM output to Vocabulary Size
        # So that we can predict the next word
        self.fc = tf.keras.layers.Dense(output_size)

    def call(self,x,hidden,cell):
        # Embedding
        x = self.embedding(x)
        # Initialize Decoder's LSTM with context vector (hidden, cell) from Encoder
        output, hidden, cell = self.lstm(x, initial_state=[hidden, cell])
        # Pass LSTM output to Dense layer to predict next word
        output = self.fc(output)
        return output, hidden, cell

# The Main Class: Connect Encoder and decoder
# seq2Seq Model
class Seq2Seq(tf.keras.Model):
    def __init__(self,encoder,decoder):
        super(Seq2Seq,self).__init__()
        self.encoder = encoder
        self.decoder = decoder

    def call(self, inputs, training = False):
        src,tgt = inputs

        # step 1: We need to pass English Sentence through Encoder to get the context vector
        hidden, cell = self.encoder(src)
        outputs = []
        # the fisrt input to the decoder is ALWAYS <SOS> token

        input_token = tgt[:,0:1]
        # we will loop as many times as the lenght of the target sentence.
        # We will use .shape[1] (static integer) to avoid dynamic shape error
        target_len = tgt.shape[1]
        for t in range(1, target_len):
            # step 2: We will pass current token + previous state to decoder
            output, hidden, cell = self.decoder(input_token,hidden,cell)
            outputs.append(output)

            # step 3: We will decide next input (Teacher Forcing)
            if training and random.random() < 0.5:
                # teacher Forcing: use the actual next word from the dataset as input for the next time step
                # it helps model learn faster in early stages
                input_token = tgt[:, t:t+1]
            else:
                # Inference/Validation: It will feed the word the model just predicted
                input_token = tf.argmax(output,axis = -1, output_type=tf.int32)

        # concatenate all time steps into one big tensor
        return tf.concat(outputs,axis=1) if outputs else tf.zeros((tf.shape(src)[0],1,len(hindi_vocab)))

# Phase 3: Training Setup

embed_size = 50
hidden_size = 100

# let's instantiate the Main Seq2Seq model
model = Seq2Seq(
    Encoder(len(eng_vocab), embed_size, hidden_size),
    Decoder(len(hindi_vocab), embed_size, hidden_size)
)

optimizer = tf.keras.optimizers.Adam(0.01) # Updates the weight after each iteration

# loss function:
# from_logits=True means the model outputs raw scores (logits), not probabilities
# reduction='none' means we want to calculate loss for each token individually
# so that we can ignore padding tokens (0)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')

# There is one Training Step C++ graph for speed using @tf.function
@tf.function # This compiles Python -> TensorFlow C++ Graph for speed
def train_step(src,tgt):
    with tf.GradientTape() as tape:
        # Forward Pass: Get prediction
        preds = model([src,tgt], training=True)

        # calculate loss, but ignore the <PAD> tokens (zoers)
        # we don't wamt the model to learn to predict padddig
        mask = tf.cast(tgt[:,1:] != 0, tf.float32)
        loss = loss_fn(tgt[:,1:],preds) * mask

        # we will find the average loss over actual words
        mean_loss = tf.reduce_sum(loss) / tf.reduce_sum(mask)

    # backward pass: Calculate Gradients and update weight
    grads = tape.gradient(mean_loss,model.trainable_variables)
    optimizer.apply_gradients(zip(grads,model.trainable_variables)) # the learning happens
    return mean_loss

# Phase 4: Execution (Train and Test)
print(f'Starting training on {len(data)} sentences....')

# training Loop
for epoch in range(101):
    loss = train_step(src_data,tgt_data)
    if epoch %20 == 0:
        print(f"Epoch {epoch}, Loss: {loss.numpy():.4f}")

# Inference Function: Here it uses the trained model to trnaslate new senteces

def translate(sentence):
    # 1. We will preprocess the input English sentence
    indices = [eng_vocab.get(t,0) for t in sentence.split()]
    indices = [eng_vocab['<SOS>']] + indices + [eng_vocab['<EOS>']]
    src = tf.convert_to_tensor([indices]) # We are adding batch dimensions

    #2. Get the context vector from encoder
    hidden, cell = model.encoder(src)

    #3. Start Decoding
    input_token = tf.convert_to_tensor([[hindi_vocab['<SOS>']]])
    result_tokens = []

    inv_vocab = {v: k for k, v in hindi_vocab.items()}
    # reverse vocab : It converts the word IDs(int) back to words(string)

    # loop until we hit <EOS> or max length
    for i in range(15):
        output, hidden, cell = model.decoder(input_token,hidden,cell)
        # we will pick the word with highest probability
        predicted_id = tf.argmax(output,axis=-1).numpy()[0,0]

        if predicted_id == hindi_vocab['<EOS>']:
            break
        result_tokens.append(inv_vocab.get(predicted_id,'?'))

        # feed this prediction as input for the next step
        input_token = tf.convert_to_tensor([[predicted_id]])
    return ' '.join(result_tokens)


print('Translation Examples:')
test_sentences = ['I am happy','He is angry','We are ready']
for s in test_sentences:
    print(f'Input: {s}')
    print(f'Output: {translate(s)}')
    print("=="*20)

10
English Vocab Size:  21
Hindi Vocab Size:  27
{'<PAD>': 0, '<SOS>': 1, '<EOS>': 2, 'I': 3, 'am': 4, 'happy': 5, 'You': 6, 'are': 7, 'sad': 8, 'She': 9, 'is': 10, 'tired': 11, 'We': 12, 'hungry': 13, 'He': 14, 'angry': 15, 'They': 16, 'busy': 17, 'cold': 18, 'late': 19, 'ready': 20}
{'<PAD>': 0, '<SOS>': 1, '<EOS>': 2, 'मैं': 3, 'खुश': 4, 'हूँ': 5, 'तुम': 6, 'उदास': 7, 'हो': 8, 'वह': 9, 'थकी': 10, 'हुई': 11, 'है': 12, 'हम': 13, 'भूखे': 14, 'हैं': 15, 'गुस्से': 16, 'में': 17, 'वे': 18, 'व्यस्त': 19, 'मुझे': 20, 'ठंड': 21, 'लग': 22, 'रही': 23, 'देर': 24, 'से': 25, 'तैयार': 26}
Source Data:  [[ 1  3  4  5  2]
 [ 1  6  7  8  2]
 [ 1  9 10 11  2]
 [ 1 12  7 13  2]
 [ 1 14 10 15  2]
 [ 1 16  7 17  2]
 [ 1  3  4 18  2]
 [ 1  6  7 19  2]
 [ 1  9 10  5  2]
 [ 1 12  7 20  2]]
Target Data:  [[ 1  3  4  5  2  0  0]
 [ 1  6  7  8  2  0  0]
 [ 1  9 10 11 12  2  0]
 [ 1 13 14 15  2  0  0]
 [ 1  9 16 17 12  2  0]
 [ 1 18 19 15  2  0  0]
 [ 1 20 21 22 23 12  2]
 [ 1  6 24 25  8  2  0]
 [ 1  9  4 12  

https://arxiv.org/pdf/1706.03762

In [ ]:
# We are building LLM from scratch using transformer Architecture

import tensorflow as tf   # TensorFlow deep learning library
import numpy as np        # Numerical operations (arrays, matrices)
import math               # Mathematical functions


# Attention Paper: https://arxiv.org/pdf/1706.03762
# =========================================================
# 1. POSITIONAL ENCODING
# Transformer does not know word order.
# So we manually add position information using sine/cosine.
# =========================================================

class PositionalEncoding(tf.keras.layers.Layer):
    def __init__(self, embed_dim, max_seq_len=500):
        super(PositionalEncoding, self).__init__()

        self.embed_dim = embed_dim

        # Create empty matrix to store positional encodings
        # Shape: (max_seq_len, embed_dim)
        pe = np.zeros((max_seq_len, embed_dim))

        # Position numbers: 0,1,2,3...
        position = np.arange(0, max_seq_len)[:, np.newaxis]

        # Scaling term used in original Transformer paper
        div_term = np.exp(
            np.arange(0, embed_dim, 2) * -(math.log(10000.0) / embed_dim)
        )

        # Apply sine to even index dimensions
        pe[:, 0::2] = np.sin(position * div_term)

        # Apply cosine to odd index dimensions
        pe[:, 1::2] = np.cos(position * div_term)

        # Add batch dimension and convert to TensorFlow tensor
        self.pe = tf.cast(pe[np.newaxis, :, :], dtype=tf.float32)

    def call(self, x):
        # x shape: (batch_size, seq_len, embed_dim)

        # Get sequence length dynamically
        seq_len = tf.shape(x)[1]

        # Add positional encoding to word embeddings
        return x + self.pe[:, :seq_len, :]


# =========================================================
# 2. MULTI HEAD ATTENTION
# Model learns which words should focus on which other words.
# =========================================================

class MultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads):
        super(MultiHeadAttention, self).__init__()

        self.embed_dim = embed_dim
        self.num_heads = num_heads

        # Each head dimension size
        self.head_dim = embed_dim // num_heads

        # Ensure divisible
        assert self.head_dim * num_heads == embed_dim

        # Linear layers to generate Q, K, V
        self.q_linear = tf.keras.layers.Dense(embed_dim)
        self.k_linear = tf.keras.layers.Dense(embed_dim)
        self.v_linear = tf.keras.layers.Dense(embed_dim)

        # Final output projection
        self.out_linear = tf.keras.layers.Dense(embed_dim)

    def split_heads(self, x, batch_size):
        """
        Split embedding into multiple attention heads
        """

        # New shape: (batch, seq_len, num_heads, head_dim)
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.head_dim))

        # Move heads dimension forward
        return tf.transpose(x, perm=[0, 2, 1, 3])
        # Output: (batch, heads, seq_len, head_dim)

    def call(self, q, k, v, mask=None):

        batch_size = tf.shape(q)[0]

        # Step 1: Create Q, K, V matrices
        Q = self.split_heads(self.q_linear(q), batch_size)
        K = self.split_heads(self.k_linear(k), batch_size)
        V = self.split_heads(self.v_linear(v), batch_size)

        # Step 2: Attention score calculation
        matmul_qk = tf.matmul(Q, K, transpose_b=True)

        # Scale scores
        dk = tf.cast(tf.shape(K)[-1], tf.float32)
        scores = matmul_qk / tf.math.sqrt(dk)

        # Apply mask if exists
        if mask is not None:
            scores += (mask * -1e9)

        # Convert to probabilities
        attention_weights = tf.nn.softmax(scores, axis=-1)

        # Multiply weights with values
        output = tf.matmul(attention_weights, V)

        # Step 3: Combine heads
        output = tf.transpose(output, perm=[0, 2, 1, 3])
        output = tf.reshape(output, (batch_size, -1, self.embed_dim))

        return self.out_linear(output)


# =========================================================
# 3. FEED FORWARD NETWORK
# Small neural network after attention
# =========================================================

class FeedForward(tf.keras.layers.Layer):
    def __init__(self, embed_dim, ff_dim):
        super(FeedForward, self).__init__()

        self.fc1 = tf.keras.layers.Dense(ff_dim, activation='relu')
        self.fc2 = tf.keras.layers.Dense(embed_dim)

    def call(self, x):
        return self.fc2(self.fc1(x))


# =========================================================
# 4. ENCODER LAYER
# =========================================================

class EncoderLayer(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, dropout_rate=0.1):
        super(EncoderLayer, self).__init__()

        self.self_attn = MultiHeadAttention(embed_dim, num_heads)
        self.ff = FeedForward(embed_dim, ff_dim)

        self.norm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)

        self.dropout1 = tf.keras.layers.Dropout(dropout_rate)
        self.dropout2 = tf.keras.layers.Dropout(dropout_rate)

    def call(self, x, training, mask):

        # Self attention
        attn_out = self.self_attn(x, x, x, mask)
        attn_out = self.dropout1(attn_out, training=training)

        # Residual connection
        out1 = self.norm1(x + attn_out)

        # Feed forward
        ff_out = self.ff(out1)
        ff_out = self.dropout2(ff_out, training=training)

        return self.norm2(out1 + ff_out)


# =========================================================
# 5. DECODER LAYER
# =========================================================

class DecoderLayer(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, dropout_rate=0.1):
        super(DecoderLayer, self).__init__()

        self.self_attn = MultiHeadAttention(embed_dim, num_heads)
        self.cross_attn = MultiHeadAttention(embed_dim, num_heads)
        self.ff = FeedForward(embed_dim, ff_dim)

        self.norm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm3 = tf.keras.layers.LayerNormalization(epsilon=1e-6)

        self.dropout1 = tf.keras.layers.Dropout(dropout_rate)
        self.dropout2 = tf.keras.layers.Dropout(dropout_rate)
        self.dropout3 = tf.keras.layers.Dropout(dropout_rate)

    def call(self, x, enc_output, training, src_mask, trg_mask):

        # Masked self attention
        attn_out = self.self_attn(x, x, x, trg_mask)
        attn_out = self.dropout1(attn_out, training=training)
        out1 = self.norm1(x + attn_out)

        # Cross attention with encoder output
        cross_out = self.cross_attn(out1, enc_output, enc_output, src_mask)
        cross_out = self.dropout2(cross_out, training=training)
        out2 = self.norm2(out1 + cross_out)

        # Feed forward
        ff_out = self.ff(out2)
        ff_out = self.dropout3(ff_out, training=training)

        return self.norm3(out2 + ff_out)


# =========================================================
# 6. FULL TRANSFORMER MODEL
# =========================================================

class Transformer(tf.keras.Model):
    def __init__(self, src_vocab_size, trg_vocab_size, embed_dim, num_heads, num_layers, ff_dim, max_len):
        super(Transformer, self).__init__()

        # Word embeddings
        self.src_embedding = tf.keras.layers.Embedding(src_vocab_size, embed_dim)
        self.trg_embedding = tf.keras.layers.Embedding(trg_vocab_size, embed_dim)

        self.positional_encoding = PositionalEncoding(embed_dim, max_len)

        # Multiple encoder and decoder layers
        self.encoder_layers = [
            EncoderLayer(embed_dim, num_heads, ff_dim)
            for _ in range(num_layers)
        ]

        self.decoder_layers = [
            DecoderLayer(embed_dim, num_heads, ff_dim)
            for _ in range(num_layers)
        ]

        self.fc_out = tf.keras.layers.Dense(trg_vocab_size)

    def create_padding_mask(self, seq):
        """
        Mask padding tokens (value 0)
        """
        seq = tf.cast(tf.math.equal(seq, 0), tf.float32)
        return seq[:, tf.newaxis, tf.newaxis, :]

    def create_look_ahead_mask(self, size):
        """
        Prevent decoder from seeing future words
        """
        mask = 1 - tf.linalg.band_part(
            tf.ones((size, size)), -1, 0
        )
        return mask[tf.newaxis, tf.newaxis, :, :]

    def call(self, inputs, training=False):

        src, trg = inputs

        # Create masks
        src_mask = self.create_padding_mask(src)
        trg_padding_mask = self.create_padding_mask(trg)
        look_ahead_mask = self.create_look_ahead_mask(tf.shape(trg)[1])
        trg_mask = tf.maximum(trg_padding_mask, look_ahead_mask)

        # Encoder
        enc_out = self.src_embedding(src)
        enc_out = self.positional_encoding(enc_out)

        for layer in self.encoder_layers:
            enc_out = layer(enc_out, training=training, mask=src_mask)

        # Decoder
        dec_out = self.trg_embedding(trg)
        dec_out = self.positional_encoding(dec_out)

        for layer in self.decoder_layers:
            dec_out = layer(
                dec_out,
                enc_output=enc_out,
                training=training,
                src_mask=src_mask,
                trg_mask=trg_mask
            )

        return self.fc_out(dec_out)


# =========================================================
# 7. SIMPLE DATASET
# =========================================================

data = [
    ("I love AI", "मुझे AI पसंद है"),
    ("transformers are cool", "ट्रांसफॉर्मर अच्छे हैं"),
    ("hello world", "नमस्ते दुनिया"),
    ("machine learning is future", "मशीन लर्निंग भविष्य है"),
]


# =========================================================
# 8. SIMPLE TOKENIZER
# Dictionary based tokenizer
# =========================================================

class SimpleTokenizer:
    def __init__(self, sentences):

        # Special tokens
        self.vocab = {"<pad>": 0, "<sos>": 1, "<eos>": 2}
        self.index = 3

        # Build vocabulary
        for s in sentences:
            for word in s.split():
                if word not in self.vocab:
                    self.vocab[word] = self.index
                    self.index += 1

        # Reverse mapping
        self.inv_vocab = {v: k for k, v in self.vocab.items()}

    def encode(self, text):
        """
        Convert sentence into token ids
        """
        return [1] + [self.vocab.get(w, 0) for w in text.split()] + [2]

    def decode(self, tokens):
        """
        Convert token ids back into words
        """
        return " ".join([
            self.inv_vocab.get(t, "?")
            for t in tokens
            if t not in [0, 1, 2]
        ])


# Prepare sentences
eng_sentences = [pair[0] for pair in data]
hin_sentences = [pair[1] for pair in data]

src_tokenizer = SimpleTokenizer(eng_sentences)
trg_tokenizer = SimpleTokenizer(hin_sentences)


# =========================================================
# 9. HYPERPARAMETERS
# =========================================================

SRC_VOCAB = len(src_tokenizer.vocab)
TRG_VOCAB = len(trg_tokenizer.vocab)

EMBED_DIM = 32
NUM_HEADS = 4
NUM_LAYERS = 2
FF_DIM = 64
MAX_LEN = 20


# Create model
model = Transformer(
    SRC_VOCAB,
    TRG_VOCAB,
    EMBED_DIM,
    NUM_HEADS,
    NUM_LAYERS,
    FF_DIM,
    MAX_LEN
)


# =========================================================
# 10. OPTIMIZER AND LOSS
# =========================================================

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

def loss_function(real, pred):

    loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True,
        reduction='none'
    )

    loss_ = loss_object(real, pred)

    # Ignore padding tokens
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    mask = tf.cast(mask, dtype=loss_.dtype)

    loss_ *= mask

    return tf.reduce_sum(loss_) / tf.reduce_sum(mask)


# =========================================================
# 11. TRAIN STEP
# =========================================================

@tf.function
def train_step(src, trg):

    # Decoder input (remove last token)
    trg_input = trg[:, :-1]

    # Expected output (remove first token)
    trg_real = trg[:, 1:]

    with tf.GradientTape() as tape:

        predictions = model((src, trg_input), training=True)

        loss = loss_function(trg_real, predictions)

    gradients = tape.gradient(loss, model.trainable_variables)

    optimizer.apply_gradients(
        zip(gradients, model.trainable_variables)
    )

    return loss


# =========================================================
# 12. TRAINING LOOP
# =========================================================

print("Training Started...")

for epoch in range(100):

    total_loss = 0

    for src_txt, trg_txt in data:

        src = tf.constant([src_tokenizer.encode(src_txt)])
        trg = tf.constant([trg_tokenizer.encode(trg_txt)])

        loss = train_step(src, trg)

        total_loss += loss.numpy()

    if (epoch+1) % 20 == 0:
        print(f"Epoch {epoch+1}, Loss: {total_loss / len(data):.4f}")

print("Training Complete!")


# =========================================================
# 13. INFERENCE FUNCTION
# =========================================================

def translate_sentence(sentence):

    src = tf.constant([src_tokenizer.encode(sentence)])

    # Start with <sos>
    trg_indices = [1]

    for i in range(MAX_LEN):

        trg_tensor = tf.constant([trg_indices])

        predictions = model((src, trg_tensor), training=False)

        # Take last word prediction
        predictions = predictions[:, -1:, :]

        predicted_id = tf.argmax(predictions, axis=-1).numpy()[0][0]

        trg_indices.append(predicted_id)

        # Stop if <eos>
        if predicted_id == 2:
            break

    return trg_tokenizer.decode(trg_indices)


# =========================================================
# 14. TESTING
# =========================================================

test_sentence = "I love AI"
print(f"\nSource: {test_sentence}")
print(f"Translated: {translate_sentence(test_sentence)}")

test_sentence_2 = "hello world"
print(f"Source: {test_sentence_2}")
print(f"Translated: {translate_sentence(test_sentence_2)}")

Training Started...
Epoch 20, Loss: 1.6987
Epoch 40, Loss: 0.7077
Epoch 60, Loss: 0.2574
Epoch 80, Loss: 0.0880
Epoch 100, Loss: 0.0559
Training Complete!

Source: I love AI
Translated: मुझे AI पसंद है
Source: hello world
Translated: नमस्ते दुनिया


**RAG**

In [ ]:
!pip install -qU langchain langchain-google-genai langchain-community langchain-chroma chromadb

**We need to import libraries now**

In [ ]:
from langchain_community.document_loaders import TextLoader # for pdf - pypdfloader
from langchain_text_splitters import RecursiveCharacterTextSplitter # This will help us to split the docs into smaller chuncks
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate # This will help us to create prompt template
from langchain_core.output_parsers import StrOutputParser # This will help us to get output in string
from langchain_core.runnables import RunnablePassthrough # This will create a chain that we will run

In [ ]:
import os
import getpass

In [ ]:
Google_api_key = 'AIzaSyAhmtEhFheWbNGRwj2Gl3b0jqc8kVxfdoM'

os.environ['GOOGLE_API_KEY'] = Google_api_key

# bonus
# def setup_env():
#   if not os.getenv("GOOGLE_API_KEY"):
#     os.environ["GOOGLE_API_KEY"] = getpass.getpass('Enter your Google API key: ')

# setup_env()

In [ ]:
def load_and_split(filepath):
  print(f'Loading data')
  loader = TextLoader(filepath)
  docs = loader.load()

  splitter = RecursiveCharacterTextSplitter(chunk_size = 500, chunk_overlap = 200)

  splits = splitter.split_documents(docs)
  print(f'Splits {len(splits)} chunks')
  return splits

In [ ]:
def create_rag_chain(splits):
  print('Vectore Store')
  embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001",task_type="retrieval_document")
  vectorStore = Chroma.from_documents(documents=splits, embedding=embeddings)
  retriver = vectorStore.as_retriever() #This is retriver object

  ## LLM
  llm = ChatGoogleGenerativeAI(model = 'gemini-2.5-flash',temperature=0)

  template = """
  Answer the question based on the follwing context: {context}
  Question: {question}
  Helpful answer: """

  prompt = ChatPromptTemplate.from_template(template)

  def formatDocs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

  chain = (
      {'context': retriver | formatDocs, 'question': RunnablePassthrough()}
       | prompt
       | llm
       | StrOutputParser()
  )
  return chain

In [ ]:
file_path = '/content/harrypotter.txt'
splits = load_and_split(file_path)
rag_chain = create_rag_chain(splits)

Loading data
Splits 15 chunks
Vectore Store


In [ ]:
message = input('Ask question related to harry potter....')
output = rag_chain.invoke(message)
print(output)

Ask question related to harry potter....Who is dumbledore
Dumbledore is a character who begins preparing Harry for Voldemort's defeat and is later killed by Severus Snape.
