<a href="https://colab.research.google.com/github/maheshkumar30/Intellipaat-DataScience/blob/main/MLP_FCNN_DenseLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as f



**We will define the Fully Connected Neural Network Arch**


In [16]:
class SimpleFCNN(nn.Module):
    # input size : Number of input fearures
    # hidden size : Neurons in hidden layer
    # output size : Final output neurons
    def __init__(self,input_size,hidden_size,output_size):
        super(SimpleFCNN,self).__init__()
        # First Linear Layer (input --> Hidden)
        self.fc1 = nn.Linear(input_size,hidden_size)

        # Second Linear Layer (Hidden --> Output)
        self.fc2 = nn.Linear(hidden_size,output_size)

    # Now We will define forward Pass (how exactly my data is flowing through the NN)
    def forward(self,x):

        # We will pass input through  first linear layer
        x=self.fc1(x)

        # We will apply Activation Function (for example Relu)
        x = f.relu(x)

        # Now we will pass the result through the second linear layer(output layer)
        x = self.fc2(x)

        return x #


In [17]:
model = SimpleFCNN(10,5,2)
print(model)

SimpleFCNN(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=2, bias=True)
)


**Let's feed data to my model**

In [18]:
dummyData = torch.tensor([
    [0.9, 0.8, 0.95, 0.85, 0.9, 0.88, 0.92, 0.87, 0.91, 0.89], # Class High
    [0.93, 0.85, 0.9, 0.88, 0.94, 0.9, 0.86, 0.92, 0.89, 0.91], # Class High
    [0.1, 0.2, 0.05, 0.15, 0.1, 0.12, 0.08, 0.13, 0.09, 0.11], # Class Low
    [0.07, 0.18, 0.1, 0.14, 0.09, 0.2, 0.05, 0.16, 0.12, 0.08] # Class Low
])

y = torch.tensor([1,1,0,0])

# this way we will call forward function that we defined
output = model(dummyData)
print(output)

tensor([[-0.2535,  0.3958],
        [-0.2567,  0.3956],
        [-0.2232,  0.3091],
        [-0.2235,  0.3105]], grad_fn=<AddmmBackward0>)


In [19]:
dummyData.dtype,dummyData.device

(torch.float32, device(type='cpu'))

In [22]:
prediction = torch.argmax(output,dim =1)
print(prediction)

tensor([1, 1, 1, 1])


**Back propagation**

In [23]:
import torch.optim as optim # Optimizer
criteria = nn.CrossEntropyLoss()  #Loss Function
optimizer = optim.SGD(model.parameters(), lr = 0.01)  #Gradient Descent (Optimzation)

In [24]:
epoch = 50
for i in range(epoch):
    prediction = model(dummyData)
    loss = criteria(prediction,y)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 20 ==0:
        print(f"Epoch  [{i+1}/{epoch}],loss : {loss.item():.4}")
result = (model(dummyData))

In [25]:
prediction = torch.argmax(result,dim=1)
print(prediction)

tensor([1, 1, 0, 0])
