<a href="https://colab.research.google.com/github/maheshkumar30/Intellipaat-DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**
Numerical Python
1. It is used to create arrays and also manipulate
2. We have so many mathamatical operations(basic maths,algebra,linear algebra,stats)
3. We can also have some modules like random with can generate,uniform,different data distribution.
4. We have basic stats built in methods in my numpy for more advance stats methods(**scipy**)



In [1]:
pip install numpy

Implementation of NumPy Documentation

In [2]:
import numpy as np

**Lets create our very first array**

In [3]:
a=np.array([1,2,3],dtype=float)
print(a)
print(type(a))
print(a.dtype)

[1. 2. 3.]
<class 'numpy.ndarray'>
float64


**Attributes for array**
1. .shape --> shape of an array(each dimension having how many elements)
2. .ndim --> It tells about the dimension of an array

In [4]:
print(a.shape)
print(a.ndim)

(3,)
1


**Zero Dimensional array**

When we have only 1 scalar value with no direction involved is what we refer as zero dimension

In [5]:
a=np.array(12)
print(a.shape)
print(a.ndim)

()
0


**One Dimensional array**

In [6]:
a=np.array([1,2,3],dtype=float)
print(a)
print(type(a))
print(a.dtype)

[1. 2. 3.]
<class 'numpy.ndarray'>
float64


**Two dimensional array**


In [7]:
a2 =np.array([[1,2],
              [3,4]])
print(a2.shape)
print(a2.ndim)
print(a2)

(2, 2)
2
[[1 2]
 [3 4]]


**Three Dimensional Data**

In [8]:
a=np.array([[1,2,3],
            [4,5,6],
             [7,8,9]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [9]:
a=np.array([[1,2,3],
            [4,5,6],
             [7,8,9]])
print(a+a)
print(a*a)
print(a//a)
print(a**a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[        1         4        27]
 [      256      3125     46656]
 [   823543  16777216 387420489]]


In [10]:
a=np.array([[[1,2,3]]])

**ndmin--> parameter --> that defines  the dimension of array**

In [11]:
a=np.array([[[[1,2,3,4,5]]]])
print(a.ndim)
print(a.shape)

4
(1, 1, 1, 5)


**Shape and Reshaping of an array**
1. Shape should be always the multiple of the number of elements


In [12]:
a=np.array([[[1,2,3],
             [4,5,6]],

            [[7,8,9],
            [10,11,12]]])
print(a)
print(a.shape)
print(a.ndim)
print(a.reshape(3,4))


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Identity Matrix**
1. Square matix --> rows and coloms are equal
2. diagonal elements are equal to 1
3. By default the dtype of identity matrix is float

In [13]:
# method --> np.identity(n)  ==> n==m==n
i=np.identity(3,dtype=int)
i


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**np.eye()** -> This allows you to create something like identity matrix for any shape

**k= +ve** value it shift the rows upward
**k = -ve ** value it shift the rows downward


In [14]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [15]:
np.eye(3,4,dtype=int,k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

##** Broadcasting**
1. If you add 1 dimensional array to 2D array,numpy will automatically expand the smaller array to the higher dimension array to match the shape

In [16]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
c=a+b
print(a)
print()
print(b)
print()
print(c)

[[1 2 3]
 [4 5 6]]

[7 8 9]

[[ 8 10 12]
 [11 13 15]]


**Some other ways to create an array**


In [17]:
#np.zeros() -> It gives all the element the shape as zero
np.zeros((4,3),dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones((4,4),dtype=int)*22

array([[22, 22, 22, 22],
       [22, 22, 22, 22],
       [22, 22, 22, 22],
       [22, 22, 22, 22]])

In [19]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## **Mathematical methods through numpy**

In [20]:
a=np.array([1,2,3,4,5],ndmin=2)
#methods
print(f"Sum of all elements are: {np.sum(a)}")
print(f"Mean of the elements are: {np.mean(a)}")
print(f"Variance of the elements are: {np.var(a)}")
print(f"Standard Deviation of the elements are: {np.std(a)}")
print(f"Minimum of the elements are: {np.min(a)}")
print(f"Maximum of the elements are: {np.max(a)}")
print(f"product of all elments are: {np.prod(a)}")
print(f"Cummulative sum of all elements are: {np.cumsum(a)}")

Sum of all elements are: 15
Mean of the elements are: 3.0
Variance of the elements are: 2.0
Standard Deviation of the elements are: 1.4142135623730951
Minimum of the elements are: 1
Maximum of the elements are: 5
product of all elments are: 120
Cummulative sum of all elements are: [ 1  3  6 10 15]


**Random methods**

In [21]:
# np.random.rand((n)) --> the value will be in between 0 and 1| n --> number of elements
np.random.rand((3))

array([0.85780093, 0.03673252, 0.92325868])

In [22]:
np.random.randint(1,10)

4

In [23]:
np.random.randint(1,10,size=(2,3))

array([[3, 3, 8],
       [3, 3, 4]])

In [24]:
# np.random.shuffle()
a=np.array([1,2,3,4,5])
np.random.shuffle(a)

In [25]:
a=np.random.randint(5,60,size=(3,2,3))
b=a.reshape(6,3)
print(b)

[[28 31 47]
 [38 11 10]
 [31 23 46]
 [24 10  7]
 [37 11 20]
 [18 47 41]]


**Matrix Manipulation**


In [26]:
a=np.array([[1,2,3],[4,5,6]])
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

**Flatten --> It converts all the dimensions of data into one dimensions**

In [27]:
a2=a.flatten()

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a2[3]=59

In [30]:
a2.ravel()

array([ 1,  2,  3, 59,  5,  6])

**view() --> It makes a shallow copy of data**

In [31]:
aa=np.array([1,2,3])
a=aa.view()
a[1] = 20
print(a)
print(aa)

[ 1 20  3]
[ 1 20  3]


**Copy() --> It will make an independent array**

In [32]:
aa=np.array([1,2,3])
a=aa.copy()
a[1] = 20
print(a)
print(aa)

[ 1 20  3]
[1 2 3]


**hstack() --> It stacks arrays horizontally(side by side)**

In [33]:
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.hstack((a,b)))

[1 2 3 5 6 7]


**vstack --> It stacks array vertically(top to bottom)**

In [34]:
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.vstack((a,b)))

[[1 2 3]
 [5 6 7]]


**Column_stack() --> stacks 1D array as columns into a 2D array**

In [35]:
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.column_stack((a,b)))


[[1 5]
 [2 6]
 [3 7]]


**row_stack() --> stacks 1D array as rows**

In [36]:
import warnings
warnings.filterwarnings("ignore")

In [37]:
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.row_stack((a,b)))

[[1 2 3]
 [5 6 7]]


**np.where() ==> It finds the indicies of elements that meets our condition**

In [38]:
a=np.array([10,20,30,40,50,30])
#np.where(condition)
ans=np.where(a==30)
print(ans)
print(ans[0])

(array([2, 5]),)
[2 5]


In [39]:
#we are replacing all values that is less than 35 with 0 and others will remain as it is
n_a=np.where(a<35,0,a)
n_a

array([ 0,  0,  0, 40, 50,  0])

**How we will implement in 2D data**

**Elements that are greater than 3 ==> True --- rest will be false**

In [40]:
a=np.array([[1,2,3],[7,8,9]])
ans=np.where(a>3,5,a)
print(f"Row Indices:{a[0]}")
print(f"Column Indices:{a[1]}")

Row Indices:[1 2 3]
Column Indices:[7 8 9]


##**Practice**

**Q1**
* Create a numpy array with shaped of 3x3 that has all elements as 0
* Create a numpy array with shape of 3X3 that has all elements as 1
* Create a numpy array with shape of 3X3 that has all elements as 14

In [41]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
a=np.full((3,3),14)
a

array([[14, 14, 14],
       [14, 14, 14],
       [14, 14, 14]])

**Create a random array,with the range 0-1000,with a size 50**
**Step 2 ==> Perform the following operations on the same**
* print the first ten elements of the array
* print the last ten elements of the array
* print the elements from the indexes 10-50
* print the elements at the index 22
* print the array using negative indexing
*  print the last ten elements of the array using negative indexing.

In [44]:
a=np.random.randint(0,1000,size=50)
b=a[0:11]
print("First Ten elements of array:",b)
print()
c=a[:-11:-1]
print("Last ten elemts of the array:",c)
print()
print("the elements from the indexes 10-50:",a[10:50])
print()
print(a[22])
print()
print("the last ten elements of the array using negative indexing.",a[-10:])

First Ten elements of array: [751 691  86 659 342 528 570 198 281 740 689]

Last ten elemts of the array: [900 748 241 527 948 500 179 937 379 334]

the elements from the indexes 10-50: [689 269 306 433 560 682 986 347 184 472 332 486 969 291 585 850 675 933
 914 900 590 189 680 348 338 807 288 563 350 508 334 379 937 179 500 948
 527 241 748 900]

969

the last ten elements of the array using negative indexing. [334 379 937 179 500 948 527 241 748 900]


In [45]:
a=np.array([1,2,3,4,5])
b=np.append(a,22)
print(b)
c=np.insert(a,0,59)
print(c)
d=np.insert(a,3,40)
print(d)
d[5]=50
print(d)
f=np.delete(d,-1)
print(f)
g=np.sort(f)
print(g)



[ 1  2  3  4  5 22]
[59  1  2  3  4  5]
[ 1  2  3 40  4  5]
[ 1  2  3 40  4 50]
[ 1  2  3 40  4]
[ 1  2  3  4 40]
